resources:
  - name: automation
    type: git
    icon: github
    source:
      uri: https://github.com/debanne/deploy-automation.git
      branch: ((source_branch))
  - name: config
    type: git
    icon: github
    source:
      uri: https://github.com/debanne/deploy-config.git
      branch: master
  - name: image
    type: registry-image
    icon: docker
    source:
      repository: busybox
  - name: trigger
    type: semver
    icon: play-circle-outline
    source:
      driver:      git
      uri:         git@github.com:debanne/pipelines-compass.git
      branch:      master
      file:        triggers/deploy-((env_name))-concourse-training
      private_key: |
        ((github-private-key))
      git_user:    "((git-commit-name)) <((git-commit-email))>"
      initial_version: 1.0.0

jobs:
  - name: deploy
    plan:
      - in_parallel:
        - get: trigger
          trigger: true
        - get: automation
        - get: image
        - get: config
      - task: deploy
        image: image
        config:
          platform: linux
          inputs:
          - name: config
          params:
            COLOR: ((color))
            ENV_NAME: ((env_name))
            VERSION: ((component-version))
          run:
            path: sh
            args:
              - "-c"
              - |
                echo "Deploying '$COLOR' on $ENV_NAME v$VERSION..."
                sleep 10
                echo "OK!"