resources:
  - name: automation
    type: git
    icon: github
    source:
      uri: git@github.com:debanne/deploy-automation.git
      branch: master
      private_key: ((github-private-key))
  - name: automation-staging
    type: git
    icon: github
    source:
      uri: git@github.com:debanne/deploy-automation.git
      branch: staging
      private_key: ((github-private-key))
  - name: automation-prod
    type: git
    icon: github
    source:
      uri: git@github.com:debanne/deploy-automation.git
      branch: prod
      private_key: ((github-private-key))
#  - name: config
#    type: git
#    icon: github
#    source:
#      uri: git@github.com:debanne/deploy-config.git
#      branch: master
#      private_key: ((github-private-key))
  - name: image
    type: registry-image
    icon: docker
    source:
      repository: gstack/gk-ops
  - name: sandbox-config
    type: git
    icon: github
    source:
      uri: git@github.com:debanne/deploy-config.git
      branch: master
      private_key: |
        ((github-private-key))
      paths:
        - sandbox/*
  - name: staging-config
    type: git
    icon: github
    source:
      uri: git@github.com:debanne/deploy-config.git
      branch: master
      private_key: |
        ((github-private-key))
      paths:
        - staging/*
  - name: prod-config
    type: git
    icon: github
    source:
      uri: git@github.com:debanne/deploy-config.git
      branch: master
      private_key: |
        ((github-private-key))
      paths:
        - prod/*
  - name: trigger-sandbox
    type: semver
    icon: play-circle-outline
    source:
      driver:      git
      uri:         git@github.com:debanne/pipelines-compass.git
      branch:      master
      file:        triggers/deploy-sandbox-concourse-training
      private_key: |
        ((github-private-key))
      git_user:    "((git-commit-name)) <((git-commit-email))>"
      initial_version: 1.0.0
  - name: trigger-staging
    type: semver
    icon: play-circle-outline
    source:
      driver:      git
      uri:         git@github.com:debanne/pipelines-compass.git
      branch:      master
      file:        triggers/deploy-staging-concourse-training
      private_key: |
        ((github-private-key))
      git_user:    "((git-commit-name)) <((git-commit-email))>"
      initial_version: 1.0.0
  - name: trigger-prod
    type: semver
    icon: play-circle-outline
    source:
      driver:      git
      uri:         git@github.com:debanne/pipelines-compass.git
      branch:      master
      file:        triggers/deploy-prod-concourse-training
      private_key: |
        ((github-private-key))
      git_user:    "((git-commit-name)) <((git-commit-email))>"
      initial_version: 1.0.0

jobs:
  - name: repipe-sandbox
    serial: true
    plan:
      - get: automation
      - get: config
        resource: sandbox-config
        trigger: true
      - get: image
      - task: prepare-pipeline
        image: image
        input_mapping:
          automation: automation
        params:
          ENV_NAME: sandbox
        file: automation/ci/repipe/tasks/prepare-pipeline.yml
      - set_pipeline: deploy-sandbox
        file: automation/ci/deploy-infra/pipeline.yml
        var_files:
          - automation/ci/deploy-infra/config/versions.yml
          - config/sandbox/settings.yml
        vars:
          env_name: sandbox
          source_branch: master
          next_env: staging
      - put: trigger-sandbox
        params: { bump: patch }
  - name: repipe-staging
    serial: true
    plan:
      - get: automation-staging
      - get: config
        resource: staging-config
        trigger: true
      - get: image
      - task: prepare-pipeline
        image: image
        input_mapping:
          automation: automation-staging
        params:
          ENV_NAME: staging
        file: automation-staging/ci/repipe/tasks/prepare-pipeline.yml
      - set_pipeline: deploy-staging
        file: automation-staging/ci/deploy-infra/pipeline.yml
        var_files:
          - automation-staging/ci/deploy-infra/config/versions.yml
          - config/staging/settings.yml
        vars:
          env_name: staging
          source_branch: staging
          next_env: prod
      - put: trigger-staging
        params: { bump: patch }
  - name: repipe-prod
    serial: true
    plan:
      - get: automation-prod
      - get: config
        resource: prod-config
        trigger: true
      - get: image
      - get: automation
        resource: automation-prod
      - task: prepare-pipeline
        image: image
        params:
          ENV_NAME: prod
        file: automation/ci/repipe/tasks/prepare-pipeline.yml
      - set_pipeline: deploy-prod
        file: automation/ci/deploy-infra/pipeline.yml
        var_files:
          - automation/ci/deploy-infra/config/versions.yml
          - config/prod/settings.yml
        vars:
          env_name: prod
          source_branch: prod
      - put: trigger-prod
        params: { bump: patch }

